const db = [
    // ==========================================
    // FAMÍLIA: ALICE
    // ==========================================
    {"nome": "Alice A703", "projecao": "Forte", "cor": "W: 30% | F: 70%", "nucleo": "Aço (Sólido)", "preco_min": 37, "preco_max": 58, "resposta": "Rápida", "ambiente": "Ambos", "qualidade": "C-", "nota": "5.5", "amaciamento": "Rápido (minutos)", "durabilidade": "Longa (6+ meses)", "clima": "Baixa (Estável)", "revestimento": "Ligas / Níquel (Níquel)", "fixacao": "Ball-end", "tolerancia": "Média", "confiabilidade_preco": "Média"},
    {"nome": "Alice A708", "projecao": "Moderada", "cor": "W: 75% | F: 40%", "nucleo": "Sintético (Nylon)", "preco_min": 60, "preco_max": 78, "resposta": "Moderada", "ambiente": "Interno", "qualidade": "C+", "nota": "8.50", "amaciamento": "Médio (1-3 dias)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Alumínio / Níquel (Níquel)", "fixacao": "Ball-end", "tolerancia": "Alta", "confiabilidade_preco": "Média"},
    {"nome": "Alice A747", "projecao": "Moderada", "cor": "W: 60% | F: 50%", "nucleo": "Sintético (Nylon)", "preco_min": 120, "preco_max": 158, "resposta": "Rápida", "ambiente": "Interno", "qualidade": "C+", "nota": "9.00", "amaciamento": "Médio (1-3 dias)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Alumínio / Prata", "fixacao": "Ball-end", "tolerancia": "Alta", "confiabilidade_preco": "Média"},

    // ==========================================
    // FAMÍLIA: CORELLI
    // ==========================================
    {"nome": "Corelli Alliance", "projecao": "Forte", "cor": "W: 60% | F: 70%", "nucleo": "Sintético (Kevlar)", "preco_min": 480, "preco_max": 640, "resposta": "Rápida", "ambiente": "Ambos", "qualidade": "A-", "nota": "8.60", "amaciamento": "Lento (4+ dias)", "durabilidade": "Longa (6+ meses)", "clima": "Baixa (Estável)", "revestimento": "Alumínio / Prata", "fixacao": "Ball/Loop", "tolerancia": "Média", "confiabilidade_preco": "Média"},
    {"nome": "Corelli Cantiga", "projecao": "Forte", "cor": "W: 70% | F: 80%", "nucleo": "Sintético", "preco_min": 404, "preco_max": 565, "resposta": "Rápida", "ambiente": "Ambos", "qualidade": "A", "nota": "9.00", "amaciamento": "Rápido (minutos)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Alumínio / Prata", "fixacao": "Ball/Loop", "tolerancia": "Média", "confiabilidade_preco": "Média"},
    {"nome": "Corelli Crystal", "projecao": "Moderada", "cor": "W: 75% | F: 40%", "nucleo": "Sintético (Stabalon)", "preco_min": 306, "preco_max": 442, "resposta": "Moderada", "ambiente": "Interno", "qualidade": "B", "nota": "8.10", "amaciamento": "Médio (1-3 dias)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Alumínio / Prata", "fixacao": "Ball/Loop", "tolerancia": "Alta", "confiabilidade_preco": "Média"},
    {"nome": "Corelli Solea", "projecao": "Moderada-Alta", "cor": "W: 60% | F: 60%", "nucleo": "Sintético Multifilamento", "preco_min": 534, "preco_max": 776, "resposta": "Muito Rápida", "ambiente": "Ambos", "qualidade": "A", "nota": "9.20", "amaciamento": "Médio (1-2 dias)", "durabilidade": "Alta (4-6 meses)", "clima": "Média (Estável)", "revestimento": "Ligas Inovadoras", "fixacao": "Ball-end/Loop-end", "tolerancia": "Alta", "confiabilidade_preco": "Alta"},

    // ==========================================
    // FAMÍLIA: D'ADDARIO / KAPLAN
    // ==========================================
    {"nome": "D'Addario Ascenté", "projecao": "Moderada", "cor": "W: 60% | F: 60%", "nucleo": "Sintético", "preco_min": 219, "preco_max": 282, "resposta": "Rápida", "ambiente": "Interno", "qualidade": "C+", "nota": "8.20", "amaciamento": "Rápido (minutos)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Monel / Alumínio", "fixacao": "Ball-end", "tolerancia": "Alta", "confiabilidade_preco": "Média"},
    {"nome": "D'Addario Helicore", "projecao": "Forte", "cor": "W: 40% | F: 85%", "nucleo": "Aço (Entrançado)", "preco_min": 440, "preco_max": 560, "resposta": "Instantânea", "ambiente": "Ambos", "qualidade": "B+", "nota": "8.80", "amaciamento": "Rápido (minutos)", "durabilidade": "Longa (6+ meses)", "clima": "Baixa (Estável)", "revestimento": "Titânio / Alumínio / Prata", "fixacao": "Ball-end", "tolerancia": "Média", "confiabilidade_preco": "Média"},
    {"nome": "D'Addario Kaplan Amo", "projecao": "Forte", "cor": "W: 85% | F: 70%", "nucleo": "Sintético", "preco_min": 589, "preco_max": 737, "resposta": "Rápida", "ambiente": "Ambos", "qualidade": "A-", "nota": "9.10", "amaciamento": "Médio (1-3 dias)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Alumínio / Prata", "fixacao": "Ball-end", "tolerancia": "Média", "confiabilidade_preco": "Média"},
    {"nome": "D'Addario Kaplan Vivo", "projecao": "Muito Forte", "cor": "W: 20% | F: 90%", "nucleo": "Sintético", "preco_min": 713, "preco_max": 843, "resposta": "Instantânea", "ambiente": "Ambos", "qualidade": "A-", "nota": "9.00", "amaciamento": "Rápido (minutos)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Alumínio / Prata", "fixacao": "Ball-end", "tolerancia": "Baixa", "confiabilidade_preco": "Média"},
    {"nome": "D'Addario NS Electric", "projecao": "Alta", "cor": "W: 40% | F: 80%", "nucleo": "Aço Trançado", "preco_min": 300, "preco_max": 400, "resposta": "Rápida", "ambiente": "Estúdio/Palco", "qualidade": "B+", "nota": "8.50", "amaciamento": "Rápido (minutos)", "durabilidade": "Muito Alta (6+ meses)", "clima": "Baixa (Insensível)", "revestimento": "Metais Diversos", "fixacao": "Ball-end", "tolerancia": "Muito Alta", "confiabilidade_preco": "Baixa"},
    {"nome": "D'Addario Prelude", "projecao": "Moderada", "cor": "W: 50% | F: 60%", "nucleo": "Aço (Sólido)", "preco_min": 192, "preco_max": 245, "resposta": "Rápida", "ambiente": "Interno", "qualidade": "B-", "nota": "8.50", "amaciamento": "Rápido (minutos)", "durabilidade": "Longa (6+ meses)", "clima": "Baixa (Estável)", "revestimento": "Alumínio / Níquel", "fixacao": "Ball-end", "tolerancia": "Alta", "confiabilidade_preco": "Média"},
    {"nome": "D'Addario Pro-Arte", "projecao": "Moderada", "cor": "W: 85% | F: 40%", "nucleo": "Sintético (Nylon)", "preco_min": 253, "preco_max": 343, "resposta": "Moderada", "ambiente": "Interno", "qualidade": "B", "nota": "8.20", "amaciamento": "Médio (1-3 dias)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Alumínio / Prata", "fixacao": "Ball-end", "tolerancia": "Alta", "confiabilidade_preco": "Média"},
    {"nome": "D'Addario Zyex", "projecao": "Forte", "cor": "W: 60% | F: 80%", "nucleo": "Sintético (Zyex)", "preco_min": 350, "preco_max": 453, "resposta": "Rápida", "ambiente": "Ambos", "qualidade": "B+", "nota": "8.70", "amaciamento": "Rápido (minutos)", "durabilidade": "Longa (6+ meses)", "clima": "Baixa (Estável)", "revestimento": "Alumínio / Prata", "fixacao": "Ball-end", "tolerancia": "Média", "confiabilidade_preco": "Média"},
    {"nome": "Kaplan Golden Spiral Violin E Strings", "projecao": "Alta", "cor": "W: 45% | F: 85%", "nucleo": "Aço de Alto Carbono", "preco_min": 50, "preco_max": 80, "resposta": "Rápida", "ambiente": "Ambos", "qualidade": "A-", "nota": "8.80", "amaciamento": "Curto (1 dia)", "durabilidade": "Média (2-4 meses)", "clima": "Média", "revestimento": "Estanhado/Ouro", "fixacao": "Ball-end/Loop-end", "tolerancia": "Alta", "confiabilidade_preco": "Baixa"},

    // ==========================================
    // FAMÍLIA: DOGAL
    // ==========================================
    {"nome": "Dogal B48 Marchio Blu Blue Tag Special Alloy Violin", "projecao": "Alta", "cor": "W: 50% | F: 70%", "nucleo": "Aço Especial", "preco_min": 280, "preco_max": 380, "resposta": "Rápida", "ambiente": "Concerto", "qualidade": "A-", "nota": "8.60", "amaciamento": "Rápido (1 dia)", "durabilidade": "Muito Alta", "clima": "Baixa (Insensível)", "revestimento": "Liga Especial", "fixacao": "Ball-end", "tolerancia": "Alta", "confiabilidade_preco": "Baixa"},
    {"nome": "Dogal B488 Marchio Blu Blue Tag Special Alloy Violin", "projecao": "Alta", "cor": "W: 50% | F: 70%", "nucleo": "Aço Especial", "preco_min": 280, "preco_max": 380, "resposta": "Rápida", "ambiente": "Concerto", "qualidade": "A-", "nota": "8.60", "amaciamento": "Rápido (1 dia)", "durabilidade": "Muito Alta", "clima": "Baixa (Insensível)", "revestimento": "Liga Especial", "fixacao": "Loop-end", "tolerancia": "Alta", "confiabilidade_preco": "Baixa"},
    {"nome": "Dogal Capriccio", "projecao": "Muito Forte", "cor": "W: 40% | F: 85%", "nucleo": "Sintético", "preco_min": 392, "preco_max": 522, "resposta": "Instantânea", "ambiente": "Ambos", "qualidade": "A-", "nota": "8.90", "amaciamento": "Rápido (minutos)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Prata / Ligas Cobre", "fixacao": "Ball-end", "tolerancia": "Baixa", "confiabilidade_preco": "Média"},
    {"nome": "Dogal E170 Electrosound Chrome Electric Violin Strings", "projecao": "Alta (Amplificada)", "cor": "W: 30% | F: 90%", "nucleo": "Aço Cromo Sólido", "preco_min": 250, "preco_max": 350, "resposta": "Imediata", "ambiente": "Estúdio/Palco", "qualidade": "B+", "nota": "8.70", "amaciamento": "Rápido", "durabilidade": "Muito Alta", "clima": "Baixa (Insensível)", "revestimento": "Cromo", "fixacao": "Ball-end", "tolerancia": "Extrema", "confiabilidade_preco": "Baixa"},
    {"nome": "Dogal E1705S Electrosound 5 String Electric Violin Strings", "projecao": "Alta (Amplificada)", "cor": "W: 30% | F: 90%", "nucleo": "Aço Cromo Sólido", "preco_min": 450, "preco_max": 550, "resposta": "Imediata", "ambiente": "Estúdio/Palco", "qualidade": "B+", "nota": "8.70", "amaciamento": "Rápido", "durabilidade": "Muito Alta", "clima": "Baixa (Insensível)", "revestimento": "Cromo", "fixacao": "Ball-end", "tolerancia": "Extrema", "confiabilidade_preco": "Baixa"},
    {"nome": "Dogal E1705SMW Electrosound 5 String Electric Violin Strings", "projecao": "Alta (Amplificada)", "cor": "W: 50% | F: 80%", "nucleo": "Aço Multifilamento", "preco_min": 480, "preco_max": 580, "resposta": "Imediata", "ambiente": "Estúdio/Palco", "qualidade": "A-", "nota": "8.90", "amaciamento": "Rápido", "durabilidade": "Alta", "clima": "Baixa (Insensível)", "revestimento": "Cromo", "fixacao": "Ball-end", "tolerancia": "Extrema", "confiabilidade_preco": "Baixa"},
    {"nome": "Dogal Green Label", "projecao": "Forte", "cor": "W: 60% | F: 70%", "nucleo": "Bronze", "preco_min": 309, "preco_max": 440, "resposta": "Rápida", "ambiente": "Ambos", "qualidade": "B+", "nota": "8.50", "amaciamento": "Rápido (minutos)", "durabilidade": "Longa (6+ meses)", "clima": "Baixa (Estável)", "revestimento": "Bronze", "fixacao": "Ball-end", "tolerancia": "Média", "confiabilidade_preco": "Média"},
    {"nome": "Dogal R31 Marchio Rosso Red Tag Chrome Violin Strings", "projecao": "Muito Alta", "cor": "W: 30% | F: 85%", "nucleo": "Aço", "preco_min": 180, "preco_max": 250, "resposta": "Imediata", "ambiente": "Geral", "qualidade": "B+", "nota": "8.20", "amaciamento": "Imediato", "durabilidade": "Muito Alta", "clima": "Baixa (Insensível)", "revestimento": "Cromo", "fixacao": "Ball-end", "tolerancia": "Alta", "confiabilidade_preco": "Baixa"},
    {"nome": "Dogal T156OC Orchestra Chromesteel Violin Strings | Synthetic Gut", "projecao": "Moderada", "cor": "W: 75% | F: 50%", "nucleo": "Tripa Sintética", "preco_min": 400, "preco_max": 500, "resposta": "Média", "ambiente": "Orquestra/Câmara", "qualidade": "A", "nota": "8.90", "amaciamento": "Longo (3-5 dias)", "durabilidade": "Alta (4-6 meses)", "clima": "Baixa (Estável)", "revestimento": "Aço Cromo", "fixacao": "Ball-end", "tolerancia": "Alta", "confiabilidade_preco": "Baixa"},
    {"nome": "Dogal T156SC Soloist Chromesteel Violin Strings | Synthetic Gut Ball End", "projecao": "Alta", "cor": "W: 65% | F: 75%", "nucleo": "Tripa Sintética", "preco_min": 600, "preco_max": 800, "resposta": "Rápida", "ambiente": "Solo", "qualidade": "A", "nota": "9.10", "amaciamento": "Longo (3-5 dias)", "durabilidade": "Média-Alta (3-5 meses)", "clima": "Baixa (Estável)", "revestimento": "Aço Cromo", "fixacao": "Ball-end", "tolerancia": "Alta", "confiabilidade_preco": "Baixa"},
    {"nome": "Dogal V21 Green Tag Bronze Flatwound Violin Strings", "projecao": "Moderada", "cor": "W: 85% | F: 50%", "nucleo": "Aço de Alto Carbono", "preco_min": 90, "preco_max": 150, "resposta": "Média", "ambiente": "Estudo/Iniciante", "qualidade": "B", "nota": "7.80", "amaciamento": "Médio (2 dias)", "durabilidade": "Muito Alta", "clima": "Baixa (Insensível)", "revestimento": "Bronze Flatwound", "fixacao": "Ball-end", "tolerancia": "Alta", "confiabilidade_preco": "Baixa"},
    {"nome": "Dogal Vivaldi T81M Violin Strings MT, Stainless/Aluminum/Silver SynGut", "projecao": "Moderada-Alta", "cor": "W: 70% | F: 60%", "nucleo": "Tripa Sintética/Carbono", "preco_min": 350, "preco_max": 450, "resposta": "Rápida", "ambiente": "Câmara/Orquestra", "qualidade": "A-", "nota": "8.80", "amaciamento": "Curto (2 dias)", "durabilidade": "Alta (4-6 meses)", "clima": "Baixa (Estável)", "revestimento": "Inox/Alumínio/Prata", "fixacao": "Ball-end", "tolerancia": "Alta", "confiabilidade_preco": "Baixa"},
    {"nome": "Dogal Vivaldi T83M Violin Strings MT Synthetic Gut and Sterling Silver", "projecao": "Moderada-Alta", "cor": "W: 65% | F: 70%", "nucleo": "Tripa Sintética/Carbono", "preco_min": 400, "preco_max": 500, "resposta": "Rápida", "ambiente": "Solo/Câmara", "qualidade": "A", "nota": "9.00", "amaciamento": "Curto (2 dias)", "durabilidade": "Média-Alta (3-5 meses)", "clima": "Baixa (Estável)", "revestimento": "Prata Esterlina", "fixacao": "Ball-end", "tolerancia": "Alta", "confiabilidade_preco": "Baixa"},

    // ==========================================
    // FAMÍLIA: JARGAR
    // ==========================================
    {"nome": "Jargar Classic", "projecao": "Moderada", "cor": "W: 80% | F: 70%", "nucleo": "Aço (Entrançado)", "preco_min": 316, "preco_max": 423, "resposta": "Rápida", "ambiente": "Interno", "qualidade": "B+", "nota": "8.60", "amaciamento": "Rápido (minutos)", "durabilidade": "Longa (6+ meses)", "clima": "Baixa (Estável)", "revestimento": "Crómio / Prata", "fixacao": "Ball-end", "tolerancia": "Alta", "confiabilidade_preco": "Média"},
    {"nome": "Jargar Evoke", "projecao": "Forte", "cor": "W: 50% | F: 85%", "nucleo": "Sintético", "preco_min": 528, "preco_max": 787, "resposta": "Instantânea", "ambiente": "Ambos", "qualidade": "A-", "nota": "9.00", "amaciamento": "Rápido (minutos)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Alumínio / Prata", "fixacao": "Ball Removível", "tolerancia": "Média", "confiabilidade_preco": "Média"},
    {"nome": "Jargar Superior", "projecao": "Forte", "cor": "W: 85% | F: 75%", "nucleo": "Sintético", "preco_min": 648, "preco_max": 906, "resposta": "Rápida", "ambiente": "Ambos", "qualidade": "A", "nota": "9.10", "amaciamento": "Médio (1-3 dias)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Alumínio / Prata", "fixacao": "Ball Removível", "tolerancia": "Média", "confiabilidade_preco": "Média"},
    {"nome": "Jargar Young Talent", "projecao": "Moderada", "cor": "W: 60% | F: 65%", "nucleo": "Sintético", "preco_min": 260, "preco_max": 363, "resposta": "Rápida", "ambiente": "Interno", "qualidade": "B", "nota": "8.80", "amaciamento": "Rápido (minutos)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Alumínio / Prata", "fixacao": "Ball-end", "tolerancia": "Alta", "confiabilidade_preco": "Média"},

    // ==========================================
    // FAMÍLIA: LARSEN
    // ==========================================
    
    {"nome": "Larsen Aurora", "projecao": "Moderada", "cor": "W: 65% | F: 50%", "nucleo": "Sintético", "preco_min": 350, "preco_max": 463, "resposta": "Moderada", "ambiente": "Interno", "qualidade": "B", "nota": "8.40", "amaciamento": "Rápido (minutos)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Alumínio / Prata", "fixacao": "Ball/Loop", "tolerancia": "Alta", "confiabilidade_preco": "Média"},
    {"nome": "Larsen Il Cannone", "projecao": "Forte", "cor": "W: 60% | F: 75%", "nucleo": "Sintético", "preco_min": 700, "preco_max": 982, "resposta": "Rápida", "ambiente": "Ambos", "qualidade": "A", "nota": "9.30", "amaciamento": "Rápido (minutos)", "durabilidade": "Longa (6+ meses)", "clima": "Baixa (Estável)", "revestimento": "Alumínio / Prata", "fixacao": "Ball Removível", "tolerancia": "Média", "confiabilidade_preco": "Média"},
    {"nome": "Larsen Il Cannone Direct Focused", "projecao": "Muito Forte", "cor": "W: 20% | F: 100%", "nucleo": "Sintético", "preco_min": 963, "preco_max": 1247, "resposta": "Instantânea", "ambiente": "Ambos", "qualidade": "A+", "nota": "9.60", "amaciamento": "Rápido (minutos)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Alumínio / Prata", "fixacao": "Ball Removível", "tolerancia": "Baixa", "confiabilidade_preco": "Média"},
    {"nome": "Larsen Il Cannone Direct Focused Solist", "projecao": "Máxima", "cor": "W: 35% | F: 90%", "nucleo": "Sintético", "preco_min": 715, "preco_max": 753, "resposta": "Muito Rápida", "ambiente": "Solo frente à orquestra", "qualidade": "A+", "nota": "9.60", "amaciamento": "Rápido (horas)", "durabilidade": "Média-Alta", "clima": "Baixa (Estável)", "revestimento": "Alumínio/Prata", "fixacao": "Ball-end", "tolerancia": "Alta", "confiabilidade_preco": "Alta"},
    {"nome": "Larsen Il Cannone Gold", "projecao": "Muito Forte", "cor": "W: 60% | F: 95%", "nucleo": "Sintético", "preco_min": 1438, "preco_max": 2577, "resposta": "Instantânea", "ambiente": "Ambos", "qualidade": "A+", "nota": "9.70", "amaciamento": "Rápido (minutos)", "durabilidade": "Longa (6+ meses)", "clima": "Baixa (Estável)", "revestimento": "Ouro / Prata / Alumínio", "fixacao": "Ball Removível", "tolerancia": "Baixa", "confiabilidade_preco": "Média"},
    {"nome": "Larsen Il Cannone Silver", "projecao": "Forte", "cor": "W: 80% | F: 70%", "nucleo": "Sintético", "preco_min": 833, "preco_max": 1123, "resposta": "Rápida", "ambiente": "Ambos", "qualidade": "A", "nota": "8.50", "amaciamento": "Rápido (minutos)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Prata (Fio Ext D/G)", "fixacao": "Ball Removível", "tolerancia": "Média", "confiabilidade_preco": "Média"},
    {"nome": "Larsen Il Cannone Solist", "projecao": "Muito Forte", "cor": "W: 50% | F: 90%", "nucleo": "Sintético", "preco_min": 760, "preco_max": 1028, "resposta": "Instantânea", "ambiente": "Ambos", "qualidade": "A+", "nota": "9.50", "amaciamento": "Rápido (minutos)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Alumínio / Prata", "fixacao": "Ball Removível", "tolerancia": "Baixa", "confiabilidade_preco": "Média"},
    {"nome": "Larsen Original", "projecao": "Moderada", "cor": "W: 85% | F: 65%", "nucleo": "Sintético", "preco_min": 635, "preco_max": 791, "resposta": "Rápida", "ambiente": "Interno", "qualidade": "B+", "nota": "8.90", "amaciamento": "Rápido (minutos)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Alumínio / Prata", "fixacao": "Ball/Loop", "tolerancia": "Média", "confiabilidade_preco": "Média"},
    {"nome": "Larsen Tzigane", "projecao": "Baixa", "cor": "W: 95% | F: 10%", "nucleo": "Sintético (Nylon)", "preco_min": 609, "preco_max": 832, "resposta": "Moderada", "ambiente": "Interno", "qualidade": "A-", "nota": "8.70", "amaciamento": "Médio (1-3 dias)", "durabilidade": "Curta (até 1 mês)", "clima": "Baixa (Estável)", "revestimento": "Alumínio / Prata", "fixacao": "Ball/Loop", "tolerancia": "Alta", "confiabilidade_preco": "Média"},
    {"nome": "Larsen Virtuoso", "projecao": "Forte", "cor": "W: 40% | F: 80%", "nucleo": "Sintético", "preco_min": 663, "preco_max": 873, "resposta": "Rápida", "ambiente": "Ambos", "qualidade": "A", "nota": "9.10", "amaciamento": "Rápido (minutos)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Alumínio / Prata", "fixacao": "Ball/Loop", "tolerancia": "Média", "confiabilidade_preco": "Média"},

    // ==========================================
    // FAMÍLIA: PIRASTRO
    // ==========================================
    {"nome": "Evah Pirazzi Neo", "projecao": "Alta", "cor": "W: 45% | F: 85%", "nucleo": "Sintético", "preco_min": 1500, "preco_max": 1730, "resposta": "Muito Rápida", "ambiente": "Concerto/Solo", "qualidade": "A+", "nota": "9.50", "amaciamento": "Rápido (minutos)", "durabilidade": "Alta (4-6 meses)", "clima": "Baixa (Estável)", "revestimento": "Ouro/Alumínio/Prata", "fixacao": "Removable Ball-end", "tolerancia": "Alta", "confiabilidade_preco": "Alta"},
    {"nome": "Pirastro Aricore", "projecao": "Moderada", "cor": "W: 85% | F: 40%", "nucleo": "Sintético", "preco_min": 512, "preco_max": 633, "resposta": "Moderada", "ambiente": "Interno", "qualidade": "B+", "nota": "8.40", "amaciamento": "Médio (1-3 dias)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Alumínio / Prata", "fixacao": "Ball/Loop", "tolerancia": "Alta", "confiabilidade_preco": "Média"},
    {"nome": "Pirastro Chorda", "projecao": "Baixa", "cor": "W: 100%| F: 0%", "nucleo": "Tripa (Nua)", "preco_min": 677, "preco_max": 900, "resposta": "Lenta", "ambiente": "Interno", "qualidade": "A", "nota": "9.00", "amaciamento": "Lento (4+ dias)", "durabilidade": "Curta (até 1 mês)", "clima": "Alta (Desafina)", "revestimento": "Sem Revest. / Prata", "fixacao": "Tie-end", "tolerancia": "Baixa", "confiabilidade_preco": "Média"},
    {"nome": "Pirastro Chromcor", "projecao": "Forte", "cor": "W: 5% | F: 90%", "nucleo": "Aço (Sólido)", "preco_min": 333, "preco_max": 499, "resposta": "Instantânea", "ambiente": "Ambos", "qualidade": "B", "nota": "8.30", "amaciamento": "Rápido (minutos)", "durabilidade": "Longa (6+ meses)", "clima": "Baixa (Estável)", "revestimento": "Crómio", "fixacao": "Ball/Loop", "tolerancia": "Média", "confiabilidade_preco": "Média"},
    {"nome": "Pirastro Eudoxa", "projecao": "Baixa", "cor": "W: 100%| F: 5%", "nucleo": "Tripa", "preco_min": 867, "preco_max": 1157, "resposta": "Lenta", "ambiente": "Interno", "qualidade": "A", "nota": "9.00", "amaciamento": "Lento (4+ dias)", "durabilidade": "Curta (até 1 mês)", "clima": "Alta (Desafina)", "revestimento": "Alumínio / Prata", "fixacao": "Loop-end", "tolerancia": "Baixa", "confiabilidade_preco": "Média"},
    {"nome": "Pirastro Evah Pirazzi", "projecao": "Muito Forte", "cor": "W: 20% | F: 85%", "nucleo": "Sintético", "preco_min": 717, "preco_max": 983, "resposta": "Instantânea", "ambiente": "Ambos", "qualidade": "A", "nota": "9.30", "amaciamento": "Médio (1-3 dias)", "durabilidade": "Curta (até 1 mês)", "clima": "Baixa (Estável)", "revestimento": "Aço / Alumínio / Prata", "fixacao": "Ball/Loop", "tolerancia": "Baixa", "confiabilidade_preco": "Média"},
    {"nome": "Pirastro Evah Pirazzi Gold", "projecao": "Forte", "cor": "W: 80% | F: 80%", "nucleo": "Sintético", "preco_min": 1067, "preco_max": 1313, "resposta": "Rápida", "ambiente": "Ambos", "qualidade": "A+", "nota": "9.50", "amaciamento": "Médio (1-3 dias)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Ouro / Alumínio / Prata", "fixacao": "Ball/Loop", "tolerancia": "Média", "confiabilidade_preco": "Média"},
    {"nome": "Pirastro Flexocor Permanent", "projecao": "Forte", "cor": "W: 30% | F: 85%", "nucleo": "Aço (Entrançado)", "preco_min": 602, "preco_max": 800, "resposta": "Rápida", "ambiente": "Ambos", "qualidade": "B+", "nota": "8.50", "amaciamento": "Rápido (minutos)", "durabilidade": "Longa (6+ meses)", "clima": "Baixa (Estável)", "revestimento": "Titânio / Alumínio / Prata", "fixacao": "Ball/Loop", "tolerancia": "Média", "confiabilidade_preco": "Média"},
    {"nome": "Pirastro Gold Label", "projecao": "Moderada", "cor": "W: 80% | F: 50%", "nucleo": "Tripa", "preco_min": 528, "preco_max": 685, "resposta": "Moderada", "ambiente": "Interno", "qualidade": "A-", "nota": "8.80", "amaciamento": "Lento (4+ dias)", "durabilidade": "Curta (até 1 mês)", "clima": "Alta (Desafina)", "revestimento": "Alumínio / Prata", "fixacao": "Loop-end", "tolerancia": "Baixa", "confiabilidade_preco": "Média"},
    {"nome": "Pirastro Obligato", "projecao": "Moderada", "cor": "W: 95% | F: 30%", "nucleo": "Sintético", "preco_min": 750, "preco_max": 1003, "resposta": "Moderada", "ambiente": "Interno", "qualidade": "A", "nota": "9.20", "amaciamento": "Médio (1-3 dias)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Alumínio / Prata", "fixacao": "Ball/Loop", "tolerancia": "Alta", "confiabilidade_preco": "Média"},
    {"nome": "Pirastro Oliv", "projecao": "Baixa", "cor": "W: 100%| F: 10%", "nucleo": "Tripa", "preco_min": 963, "preco_max": 1440, "resposta": "Lenta", "ambiente": "Interno", "qualidade": "A+", "nota": "9.40", "amaciamento": "Lento (4+ dias)", "durabilidade": "Curta (até 1 mês)", "clima": "Alta (Desafina)", "revestimento": "Ouro / Alumínio / Prata", "fixacao": "Loop-end", "tolerancia": "Baixa", "confiabilidade_preco": "Média"},
    {"nome": "Pirastro Passione", "projecao": "Moderada", "cor": "W: 95% | F: 30%", "nucleo": "Tripa", "preco_min": 807, "preco_max": 1153, "resposta": "Lenta", "ambiente": "Interno", "qualidade": "A+", "nota": "9.10", "amaciamento": "Lento (4+ dias)", "durabilidade": "Curta (até 1 mês)", "clima": "Alta (Desafina)", "revestimento": "Alumínio / Prata", "fixacao": "Ball-end", "tolerancia": "Baixa", "confiabilidade_preco": "Média"},
    {"nome": "Pirastro Passione Solo", "projecao": "Forte", "cor": "W: 80% | F: 60%", "nucleo": "Tripa", "preco_min": 867, "preco_max": 1240, "resposta": "Moderada", "ambiente": "Interno", "qualidade": "A+", "nota": "9.20", "amaciamento": "Lento (4+ dias)", "durabilidade": "Curta (até 1 mês)", "clima": "Alta (Desafina)", "revestimento": "Alumínio / Prata", "fixacao": "Ball/Loop", "tolerancia": "Baixa", "confiabilidade_preco": "Média"},
    {"nome": "Pirastro Perpetual", "projecao": "Muito Forte", "cor": "W: 40% | F: 95%", "nucleo": "Sintético", "preco_min": 763, "preco_max": 1077, "resposta": "Instantânea", "ambiente": "Ambos", "qualidade": "A+", "nota": "9.60", "amaciamento": "Rápido (minutos)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Platina / Prata / Aço", "fixacao": "Ball Removível", "tolerancia": "Baixa", "confiabilidade_preco": "Média"},
    {"nome": "Pirastro Piranito", "projecao": "Moderada", "cor": "W: 20% | F: 70%", "nucleo": "Aço (Sólido)", "preco_min": 190, "preco_max": 270, "resposta": "Rápida", "ambiente": "Interno", "qualidade": "C+", "nota": "7.90", "amaciamento": "Rápido (minutos)", "durabilidade": "Longa (6+ meses)", "clima": "Baixa (Estável)", "revestimento": "Crómio", "fixacao": "Ball-end", "tolerancia": "Alta", "confiabilidade_preco": "Média"},
    {"nome": "Pirastro Synoxa", "projecao": "Moderada", "cor": "W: 50% | F: 50%", "nucleo": "Sintético", "preco_min": 337, "preco_max": 483, "resposta": "Rápida", "ambiente": "Interno", "qualidade": "B", "nota": "8.20", "amaciamento": "Médio (1-3 dias)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Alumínio / Prata", "fixacao": "Ball/Loop", "tolerancia": "Alta", "confiabilidade_preco": "Média"},
    {"nome": "Pirastro Tonica", "projecao": "Moderada", "cor": "W: 70% | F: 50%", "nucleo": "Sintético", "preco_min": 282, "preco_max": 433, "resposta": "Rápida", "ambiente": "Interno", "qualidade": "B+", "nota": "8.70", "amaciamento": "Médio (1-3 dias)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Alumínio / Prata", "fixacao": "Ball/Loop", "tolerancia": "Alta", "confiabilidade_preco": "Média"},
    {"nome": "Pirastro Violino", "projecao": "Baixa", "cor": "W: 95% | F: 20%", "nucleo": "Sintético", "preco_min": 269, "preco_max": 388, "resposta": "Lenta", "ambiente": "Interno", "qualidade": "B", "nota": "8.40", "amaciamento": "Médio (1-3 dias)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Alumínio / Prata", "fixacao": "Ball/Loop", "tolerancia": "Alta", "confiabilidade_preco": "Média"},
    {"nome": "Pirastro Wondertone Solo", "projecao": "Forte", "cor": "W: 40% | F: 75%", "nucleo": "Sintético", "preco_min": 500, "preco_max": 707, "resposta": "Rápida", "ambiente": "Ambos", "qualidade": "A-", "nota": "8.70", "amaciamento": "Médio (1-3 dias)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Alumínio / Prata", "fixacao": "Ball Removível", "tolerancia": "Média", "confiabilidade_preco": "Média"},

    // ==========================================
    // FAMÍLIA: THOMASTIK
    // ==========================================
    {"nome": "Thomastik Alphayue", "projecao": "Moderada", "cor": "W: 60% | F: 50%", "nucleo": "Sintético", "preco_min": 240, "preco_max": 318, "resposta": "Moderada", "ambiente": "Interno", "qualidade": "C+", "nota": "8.10", "amaciamento": "Rápido (minutos)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Alumínio / Prata", "fixacao": "Ball Removível", "tolerancia": "Alta", "confiabilidade_preco": "Média"},
    {"nome": "Thomastik Dominant", "projecao": "Moderada", "cor": "W: 70% | F: 40%", "nucleo": "Sintético (Perlon)", "preco_min": 430, "preco_max": 599, "resposta": "Moderada", "ambiente": "Ambos", "qualidade": "B+", "nota": "8.80", "amaciamento": "Médio (1-3 dias)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Alumínio / Prata", "fixacao": "Ball/Loop", "tolerancia": "Alta", "confiabilidade_preco": "Média"},
    {"nome": "Thomastik Dominant Pro", "projecao": "Forte", "cor": "W: 80% | F: 85%", "nucleo": "Sintético", "preco_min": 626, "preco_max": 881, "resposta": "Instantânea", "ambiente": "Ambos", "qualidade": "A", "nota": "9.40", "amaciamento": "Médio (1-3 dias)", "durabilidade": "Longa (6+ meses)", "clima": "Baixa (Estável)", "revestimento": "Estanho / Alumínio/Prata", "fixacao": "Ball Removível", "tolerancia": "Média", "confiabilidade_preco": "Média"},
    {"nome": "Thomastik Dynamo", "projecao": "Forte", "cor": "W: 80% | F: 40%", "nucleo": "Sintético", "preco_min": 927, "preco_max": 1170, "resposta": "Rápida", "ambiente": "Ambos", "qualidade": "A+", "nota": "9.80", "amaciamento": "Rápido (minutos)", "durabilidade": "Longa (6+ meses)", "clima": "Baixa (Estável)", "revestimento": "Estanho / Alumínio / Prata", "fixacao": "Ball Removível", "tolerancia": "Alta", "confiabilidade_preco": "Média"},
    {"nome": "Thomastik Dynamo Solo", "projecao": "Muito Forte", "cor": "W: 75% | F: 75%", "nucleo": "Sintético", "preco_min": 977, "preco_max": 1233, "resposta": "Instantânea", "ambiente": "Ambos", "qualidade": "A+", "nota": "9.90", "amaciamento": "Rápido (minutos)", "durabilidade": "Longa (6+ meses)", "clima": "Baixa (Estável)", "revestimento": "Estanho / Alumínio / Prata", "fixacao": "Ball Removível", "tolerancia": "Média", "confiabilidade_preco": "Média"},
    {"nome": "Thomastik Infeld Blue", "projecao": "Moderada", "cor": "W: 20% | F: 80%", "nucleo": "Sintético", "preco_min": 540, "preco_max": 753, "resposta": "Rápida", "ambiente": "Ambos", "qualidade": "B+", "nota": "8.50", "amaciamento": "Médio (1-3 dias)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Estanho / Alumínio / Prata", "fixacao": "Ball-end", "tolerancia": "Média", "confiabilidade_preco": "Média"},
    {"nome": "Thomastik Infeld Red", "projecao": "Moderada", "cor": "W: 90% | F: 30%", "nucleo": "Sintético", "preco_min": 563, "preco_max": 787, "resposta": "Moderada", "ambiente": "Interno", "qualidade": "B+", "nota": "8.50", "amaciamento": "Médio (1-3 dias)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Ouro / Alumínio / Prata", "fixacao": "Ball-end", "tolerancia": "Alta", "confiabilidade_preco": "Média"},
    {"nome": "Thomastik Peter Infeld (PI)", "projecao": "Muito Forte", "cor": "W: 40% | F: 90%", "nucleo": "Sintético", "preco_min": 920, "preco_max": 1246, "resposta": "Instantânea", "ambiente": "Ambos", "qualidade": "A+", "nota": "9.70", "amaciamento": "Rápido (minutos)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Platina/Ouro/Estanho/Prata", "fixacao": "Ball Removível", "tolerancia": "Baixa", "confiabilidade_preco": "Média"},
    {"nome": "Thomastik Prazision", "projecao": "Forte", "cor": "W: 10% | F: 90%", "nucleo": "Aço (Sólido)", "preco_min": 279, "preco_max": 345, "resposta": "Instantânea", "ambiente": "Ambos", "qualidade": "B", "nota": "8.20", "amaciamento": "Rápido (minutos)", "durabilidade": "Longa (6+ meses)", "clima": "Baixa (Estável)", "revestimento": "Crómio", "fixacao": "Ball-end", "tolerancia": "Média", "confiabilidade_preco": "Média"},
    {"nome": "Thomastik Rondo", "projecao": "Forte", "cor": "W: 85% | F: 80%", "nucleo": "Sintético", "preco_min": 820, "preco_max": 1010, "resposta": "Rápida", "ambiente": "Ambos", "qualidade": "A+", "nota": "9.60", "amaciamento": "Rápido (minutos)", "durabilidade": "Longa (6+ meses)", "clima": "Baixa (Estável)", "revestimento": "Estanho / Alumínio / Prata", "fixacao": "Ball Removível", "tolerancia": "Média", "confiabilidade_preco": "Média"},
    {"nome": "Thomastik Rondo Gold", "projecao": "Muito Forte", "cor": "W: 90% | F: 85%", "nucleo": "Sintético", "preco_min": 1003, "preco_max": 1420, "resposta": "Instantânea", "ambiente": "Ambos", "qualidade": "A+", "nota": "8.00", "amaciamento": "Rápido (minutos)", "durabilidade": "Longa (6+ meses)", "clima": "Baixa (Estável)", "revestimento": "Ouro / Alumínio / Prata", "fixacao": "Ball Removível", "tolerancia": "Baixa", "confiabilidade_preco": "Média"},
    {"nome": "Thomastik Spirit", "projecao": "Baixa", "cor": "W: 70% | F: 40%", "nucleo": "Sintético", "preco_min": 269, "preco_max": 363, "resposta": "Lenta", "ambiente": "Interno", "qualidade": "B-", "nota": "8.00", "amaciamento": "Médio (1-3 dias)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Alumínio / Prata", "fixacao": "Ball-end", "tolerancia": "Alta", "confiabilidade_preco": "Média"},
    {"nome": "Thomastik Spirocore", "projecao": "Forte", "cor": "W: 30% | F: 75%", "nucleo": "Aço (Entrançado)", "preco_min": 434, "preco_max": 554, "resposta": "Rápida", "ambiente": "Ambos", "qualidade": "B+", "nota": "8.60", "amaciamento": "Rápido (minutos)", "durabilidade": "Longa (6+ meses)", "clima": "Baixa (Estável)", "revestimento": "Crómio / Alumínio / Prata", "fixacao": "Ball-end", "tolerancia": "Média", "confiabilidade_preco": "Média"},
    {"nome": "Thomastik Superflexible", "projecao": "Moderada", "cor": "W: 75% | F: 50%", "nucleo": "Aço (Entrançado)", "preco_min": 350, "preco_max": 443, "resposta": "Rápida", "ambiente": "Interno", "qualidade": "B", "nota": "8.30", "amaciamento": "Rápido (minutos)", "durabilidade": "Longa (6+ meses)", "clima": "Baixa (Estável)", "revestimento": "Crómio / Alumínio", "fixacao": "Ball-end", "tolerancia": "Alta", "confiabilidade_preco": "Média"},
    {"nome": "Thomastik Ti", "projecao": "Forte", "cor": "W: 80% | F: 60%", "nucleo": "Sintético", "preco_min": 613, "preco_max": 833, "resposta": "Rápida", "ambiente": "Interno", "qualidade": "A", "nota": "9.10", "amaciamento": "Médio (1-3 dias)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Estanho / Alumínio / Prata", "fixacao": "Ball Removível", "tolerancia": "Alta", "confiabilidade_preco": "Média"},
    {"nome": "Thomastik Vision", "projecao": "Forte", "cor": "W: 20% | F: 80%", "nucleo": "Sintético", "preco_min": 392, "preco_max": 546, "resposta": "Rápida", "ambiente": "Ambos", "qualidade": "B+", "nota": "8.50", "amaciamento": "Rápido (minutos)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Alumínio / Prata", "fixacao": "Ball Removível", "tolerancia": "Média", "confiabilidade_preco": "Média"},
    {"nome": "Thomastik Vision Solo", "projecao": "Muito Forte", "cor": "W: 40% | F: 85%", "nucleo": "Sintético", "preco_min": 543, "preco_max": 697, "resposta": "Instantânea", "ambiente": "Ambos", "qualidade": "A-", "nota": "9.00", "amaciamento": "Rápido (minutos)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Alumínio / Prata", "fixacao": "Ball Removível", "tolerancia": "Baixa", "confiabilidade_preco": "Média"},
    {"nome": "Thomastik Vision Tit. Orq.", "projecao": "Forte", "cor": "W: 60% | F: 70%", "nucleo": "Sintético", "preco_min": 600, "preco_max": 773, "resposta": "Rápida", "ambiente": "Interno", "qualidade": "A-", "nota": "8.90", "amaciamento": "Rápido (minutos)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Titânio / Alumínio / Prata", "fixacao": "Ball (Titânio)", "tolerancia": "Média", "confiabilidade_preco": "Média"},
    {"nome": "Thomastik Vision Tit. Solo", "projecao": "Muito Forte", "cor": "W: 15% | F: 95%", "nucleo": "Sintético", "preco_min": 635, "preco_max": 870, "resposta": "Instantânea", "ambiente": "Externo", "qualidade": "A", "nota": "9.20", "amaciamento": "Rápido (minutos)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Titânio / Alumínio / Prata", "fixacao": "Ball (Titânio)", "tolerancia": "Baixa", "confiabilidade_preco": "Média"},

    // ==========================================
    // FAMÍLIA: WARCHAL
    // ==========================================
    {"nome": "Warchal Amber", "projecao": "Forte", "cor": "W: 85% | F: 60%", "nucleo": "Sintético (W-Core)", "preco_min": 465, "preco_max": 687, "resposta": "Rápida", "ambiente": "Ambos", "qualidade": "A+", "nota": "9.60", "amaciamento": "Médio (1-3 dias)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Hydronalium / Prata", "fixacao": "Ball-end (Helix)", "tolerancia": "Média", "confiabilidade_preco": "Média"},
    {"nome": "Warchal Ametyst", "projecao": "Moderada", "cor": "W: 30% | F: 50%", "nucleo": "Sintético", "preco_min": 363, "preco_max": 490, "resposta": "Moderada", "ambiente": "Interno", "qualidade": "B", "nota": "8.20", "amaciamento": "Médio (1-3 dias)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Hydronalium / Prata", "fixacao": "Ball-end", "tolerancia": "Alta", "confiabilidade_preco": "Média"},
    {"nome": "Warchal avantgarde A", "projecao": "Muito Alta", "cor": "W: 54% | F: 66%", "nucleo": "Metal / Tungstênio", "preco_min": 176, "preco_max": 232, "resposta": "Imediata", "ambiente": "Solo", "qualidade": "A", "nota": "8.77", "amaciamento": "Rápido", "durabilidade": "Muito Alta", "clima": "Baixa (Estável)", "revestimento": "Aço Inoxidável", "fixacao": "Ball/Loop", "tolerancia": "Alta", "confiabilidade_preco": "Baixa"},
    {"nome": "Warchal Brilliant", "projecao": "Forte", "cor": "W: 30% | F: 70%", "nucleo": "Sintético", "preco_min": 570, "preco_max": 723, "resposta": "Instantânea", "ambiente": "Ambos", "qualidade": "A", "nota": "9.00", "amaciamento": "Rápido (minutos)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Hydronalium / Prata", "fixacao": "Ball Removível", "tolerancia": "Baixa", "confiabilidade_preco": "Média"},
    {"nome": "Warchal Brilliant Vintage", "projecao": "Moderada", "cor": "W: 60% | F: 65%", "nucleo": "Sintético", "preco_min": 514, "preco_max": 703, "resposta": "Rápida", "ambiente": "Interno", "qualidade": "A-", "nota": "8.90", "amaciamento": "Rápido (minutos)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Hydronalium / Prata", "fixacao": "Loop-end", "tolerancia": "Média", "confiabilidade_preco": "Média"},
    {"nome": "Warchal Karneol", "projecao": "Baixa", "cor": "W: 90% | F: 20%", "nucleo": "Sintético", "preco_min": 372, "preco_max": 500, "resposta": "Lenta", "ambiente": "Interno", "qualidade": "B", "nota": "8.50", "amaciamento": "Médio (1-3 dias)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Hydronalium / Prata", "fixacao": "Ball-end", "tolerancia": "Alta", "confiabilidade_preco": "Média"},
    {"nome": "Warchal Russian A", "projecao": "Forte", "cor": "W: 85% | F: 75%", "nucleo": "Sintético", "preco_min": 417, "preco_max": 583, "resposta": "Rápida", "ambiente": "Interno", "qualidade": "A", "nota": "9.20", "amaciamento": "Médio (1-3 dias)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Ligas Prata", "fixacao": "Ball-end", "tolerancia": "Média", "confiabilidade_preco": "Média"},
    {"nome": "Warchal The Beast", "projecao": "Máxima", "cor": "W: 41% | F: 89%", "nucleo": "Sintético", "preco_min": 530, "preco_max": 665, "resposta": "Imediata", "ambiente": "Solo", "qualidade": "A+", "nota": "9.50", "amaciamento": "Curto", "durabilidade": "Média-Alta", "clima": "Baixa (Estável)", "revestimento": "Hydronalium / Prata", "fixacao": "Ball/Loop", "tolerancia": "Extrema", "confiabilidade_preco": "Baixa"},
    {"nome": "Warchal Timbre", "projecao": "Muito Forte", "cor": "W: 95% | F: 65%", "nucleo": "Sintético (W-Core)", "preco_min": 870, "preco_max": 1223, "resposta": "Instantânea", "ambiente": "Ambos", "qualidade": "A+", "nota": "9.80", "amaciamento": "Rápido (minutos)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Prata Pura", "fixacao": "Ball-end (Helix)", "tolerancia": "Baixa", "confiabilidade_preco": "Média"},

    // ==========================================
    // OUTRAS MARCAS E NACIONAIS
    // ==========================================
    {"nome": "6HVEB | Hill E-B Med", "projecao": "Extrema", "cor": "W: 21% | F: 87%", "nucleo": "Aço Sólido", "preco_min": 45, "preco_max": 67, "resposta": "Imediata", "ambiente": "Solo", "qualidade": "A-", "nota": "7.96", "amaciamento": "Rápido", "durabilidade": "Alta", "clima": "Baixa (Estável)", "revestimento": "Aço (Nenhum)", "fixacao": "Ball-end", "tolerancia": "Alta", "confiabilidade_preco": "Alta"},
    {"nome": "6HVEBF | Hill E-B Thick", "projecao": "Máxima", "cor": "W: 22% | F: 86%", "nucleo": "Aço Sólido", "preco_min": 45, "preco_max": 67, "resposta": "Imediata", "ambiente": "Solo", "qualidade": "A-", "nota": "7.99", "amaciamento": "Rápido", "durabilidade": "Alta", "clima": "Baixa (Estável)", "revestimento": "Aço (Nenhum)", "fixacao": "Ball-end", "tolerancia": "Muito Alta", "confiabilidade_preco": "Alta"},
    {"nome": "6HVEL | Hill E-L Med", "projecao": "Extrema", "cor": "W: 20% | F: 88%", "nucleo": "Aço Sólido", "preco_min": 42, "preco_max": 64, "resposta": "Imediata", "ambiente": "Solo", "qualidade": "A-", "nota": "7.89", "amaciamento": "Rápido", "durabilidade": "Alta", "clima": "Baixa (Estável)", "revestimento": "Aço (Nenhum)", "fixacao": "Loop-end", "tolerancia": "Alta", "confiabilidade_preco": "Alta"},
    {"nome": "6HVELF | Hill E-L Thick", "projecao": "Máxima", "cor": "W: 21% | F: 87%", "nucleo": "Aço Sólido", "preco_min": 47, "preco_max": 69, "resposta": "Imediata", "ambiente": "Solo", "qualidade": "A-", "nota": "7.92", "amaciamento": "Rápido", "durabilidade": "Alta", "clima": "Baixa (Estável)", "revestimento": "Aço (Nenhum)", "fixacao": "Loop-end", "tolerancia": "Muito Alta", "confiabilidade_preco": "Alta"},
    {"nome": "Di Pietro Studio Uno", "projecao": "Moderada", "cor": "W: 60% | F: 60%", "nucleo": "Aço (Alemão)", "preco_min": 75, "preco_max": 98, "resposta": "Rápida", "ambiente": "Ambos", "qualidade": "C+", "nota": "6.50", "amaciamento": "Rápido (minutos)", "durabilidade": "Longa (6+ meses)", "clima": "Baixa (Estável)", "revestimento": "Níquel (Níquel)", "fixacao": "Ball-end", "tolerancia": "Alta", "confiabilidade_preco": "Média"},
    {"nome": "Dominante Orchestral", "projecao": "Forte", "cor": "W: 70% | F: 60%", "nucleo": "Aço (Inox)", "preco_min": 34, "preco_max": 111, "resposta": "Rápida", "ambiente": "Ambos", "qualidade": "C+", "nota": "8.00", "amaciamento": "Rápido (minutos)", "durabilidade": "Longa (6+ meses)", "clima": "Baixa (Estável)", "revestimento": "Aço", "fixacao": "Ball-end", "tolerancia": "Alta", "confiabilidade_preco": "Média"},
    {"nome": "Dominante Orchestral (Novo)", "projecao": "Baixa", "cor": "W: 25% | F: 48%", "nucleo": "Aço / Sintético", "preco_min": 63, "preco_max": 85, "resposta": "Lenta", "ambiente": "Estudo", "qualidade": "C", "nota": "4.76", "amaciamento": "Demorado", "durabilidade": "Baixa", "clima": "Média", "revestimento": "Alumínio", "fixacao": "Ball-end", "tolerancia": "Média", "confiabilidade_preco": "Alta"},
    {"nome": "Erudithus #01", "projecao": "Forte", "cor": "W: 20% | F: 80%", "nucleo": "Aço (Inox)", "preco_min": 59, "preco_max": 85, "resposta": "Instantânea", "ambiente": "Ambos", "qualidade": "C+", "nota": "9.60", "amaciamento": "Rápido (minutos)", "durabilidade": "Longa (6+ meses)", "clima": "Baixa (Estável)", "revestimento": "Cromo / Cobre", "fixacao": "Ball-end", "tolerancia": "Média", "confiabilidade_preco": "Média"},
    {"nome": "EuroString", "projecao": "Moderada", "cor": "W: 30% | F: 60%", "nucleo": "Aço (Sólido)", "preco_min": 54, "preco_max": 70, "resposta": "Rápida", "ambiente": "Ambos", "qualidade": "C-", "nota": "6.00", "amaciamento": "Rápido (minutos)", "durabilidade": "Longa (6+ meses)", "clima": "Baixa (Estável)", "revestimento": "Ligas / Níquel (Níquel)", "fixacao": "Ball-end", "tolerancia": "Alta", "confiabilidade_preco": "Média"},
    {"nome": "For-Tune Charm", "projecao": "Forte", "cor": "W: 50% | F: 60%", "nucleo": "Sintético", "preco_min": 132, "preco_max": 178, "resposta": "Rápida", "ambiente": "Ambos", "qualidade": "B", "nota": "8.20", "amaciamento": "Rápido (minutos)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Alumínio / Prata", "fixacao": "Ball-end", "tolerancia": "Média", "confiabilidade_preco": "Média"},
    {"nome": "Giannini GEAV", "projecao": "Baixa", "cor": "W: 40% | F: 60%", "nucleo": "Aço (Sólido)", "preco_min": 40, "preco_max": 57, "resposta": "Rápida", "ambiente": "Interno", "qualidade": "D+", "nota": "3.00", "amaciamento": "Rápido (minutos)", "durabilidade": "Longa (6+ meses)", "clima": "Baixa (Estável)", "revestimento": "Ligas Metálicas", "fixacao": "Ball-end", "tolerancia": "Alta", "confiabilidade_preco": "Média"},
    {"nome": "Lenzner Goldbrokat (Só E)", "projecao": "Forte", "cor": "W: 30% | F: 85%", "nucleo": "Aço (Sólido)", "preco_min": 29, "preco_max": 62, "resposta": "Instantânea", "ambiente": "Ambos", "qualidade": "A", "nota": "9.50", "amaciamento": "Rápido (minutos)", "durabilidade": "Curta (até 1 mês)", "clima": "Baixa (Estável)", "revestimento": "Aço Nu / Banhada Ouro", "fixacao": "Ball/Loop", "tolerancia": "Alta", "confiabilidade_preco": "Média"},
    {"nome": "Mauro Calixto Padrão", "projecao": "Moderada", "cor": "W: 60% | F: 60%", "nucleo": "Sintético (Perlon)", "preco_min": 61, "preco_max": 103, "resposta": "Rápida", "ambiente": "Interno", "qualidade": "C+", "nota": "9.60", "amaciamento": "Médio (1-3 dias)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Alumínio / Ligas", "fixacao": "Ball-end", "tolerancia": "Alta", "confiabilidade_preco": "Média"},
    {"nome": "Nicola 719-NF 4/4 Fiddle Strings, Silver Wound", "projecao": "Alta", "cor": "W: 38% | F: 75%", "nucleo": "Aço / Sintético", "preco_min": 106, "preco_max": 153, "resposta": "Muito Rápida", "ambiente": "Folk", "qualidade": "B", "nota": "7.54", "amaciamento": "Rápido", "durabilidade": "Alta", "clima": "Média", "revestimento": "Prata", "fixacao": "Ball-end", "tolerancia": "Alta", "confiabilidade_preco": "Baixa"},
    {"nome": "NIG NVE804", "projecao": "Moderada", "cor": "W: 30% | F: 70%", "nucleo": "Aço (Hexagonal)", "preco_min": 39, "preco_max": 97, "resposta": "Instantânea", "ambiente": "Ambos", "qualidade": "C", "nota": "4.00", "amaciamento": "Rápido (minutos)", "durabilidade": "Longa (6+ meses)", "clima": "Baixa (Estável)", "revestimento": "Níquel Cromo (Níquel)", "fixacao": "Ball-end", "tolerancia": "Alta", "confiabilidade_preco": "Média"},
    {"nome": "Opal Titan", "projecao": "Forte", "cor": "W: 20% | F: 80%", "nucleo": "Sintético", "preco_min": 627, "preco_max": 797, "resposta": "Rápida", "ambiente": "Ambos", "qualidade": "B+", "nota": "8.30", "amaciamento": "Rápido (minutos)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Ligas Titânio / Prata", "fixacao": "Ball-end", "tolerancia": "Média", "confiabilidade_preco": "Média"},
    {"nome": "Orquezz PRO", "projecao": "Forte", "cor": "W: 80% | F: 60%", "nucleo": "Sintético (Nylon)", "preco_min": 135, "preco_max": 184, "resposta": "Rápida", "ambiente": "Interno", "qualidade": "B-", "nota": "9.00", "amaciamento": "Médio (1-3 dias)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Alumínio / Prata", "fixacao": "Ball-end", "tolerancia": "Alta", "confiabilidade_preco": "Média"},
    {"nome": "Paganini PE950 (Aço)", "projecao": "Forte", "cor": "W: 30% | F: 70%", "nucleo": "Aço (Sólido)", "preco_min": 37, "preco_max": 55, "resposta": "Rápida", "ambiente": "Ambos", "qualidade": "C", "nota": "2.00", "amaciamento": "Rápido (minutos)", "durabilidade": "Longa (6+ meses)", "clima": "Baixa (Estável)", "revestimento": "Alumínio / Ligas", "fixacao": "Ball-end", "tolerancia": "Média", "confiabilidade_preco": "Média"},
    {"nome": "Paganini PE980 (Perlon)", "projecao": "Moderada", "cor": "W: 60% | F: 50%", "nucleo": "Sintético (Perlon)", "preco_min": 58, "preco_max": 83, "resposta": "Moderada", "ambiente": "Interno", "qualidade": "C+", "nota": "2.00", "amaciamento": "Médio (1-3 dias)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Cromo", "fixacao": "Ball-end", "tolerancia": "Alta", "confiabilidade_preco": "Média"},
    {"nome": "Prim Heavy", "projecao": "Muito Forte", "cor": "W: 5% | F: 95%", "nucleo": "Aço (Sólido)", "preco_min": 263, "preco_max": 383, "resposta": "Instantânea", "ambiente": "Externo", "qualidade": "B+", "nota": "8.80", "amaciamento": "Rápido (minutos)", "durabilidade": "Longa (6+ meses)", "clima": "Baixa (Estável)", "revestimento": "Crómio", "fixacao": "Ball-end", "tolerancia": "Baixa", "confiabilidade_preco": "Média"},
    {"nome": "Prim Medium", "projecao": "Forte", "cor": "W: 10% | F: 85%", "nucleo": "Aço (Sólido)", "preco_min": 267, "preco_max": 377, "resposta": "Instantânea", "ambiente": "Externo", "qualidade": "B", "nota": "8.50", "amaciamento": "Rápido (minutos)", "durabilidade": "Longa (6+ meses)", "clima": "Baixa (Estável)", "revestimento": "Crómio", "fixacao": "Ball-end", "tolerancia": "Baixa", "confiabilidade_preco": "Média"},
    {"nome": "Pyramid 100 100 Aluminum Violin Strings Ball End", "projecao": "Moderada", "cor": "W: 33% | F: 68%", "nucleo": "Aço Sólido", "preco_min": 70, "preco_max": 113, "resposta": "Rápida", "ambiente": "Estudo", "qualidade": "C+", "nota": "6.55", "amaciamento": "Médio (dias)", "durabilidade": "Alta", "clima": "Média", "revestimento": "Alumínio", "fixacao": "Ball-end", "tolerancia": "Baixa", "confiabilidade_preco": "Baixa"},
    {"nome": "Pyramid 108 100 Gold Violin Ball End", "projecao": "Moderada-Alta", "cor": "W: 40% | F: 68%", "nucleo": "Aço Sólido", "preco_min": 105, "preco_max": 155, "resposta": "Rápida", "ambiente": "Estudo Avançado", "qualidade": "B", "nota": "7.00", "amaciamento": "Médio", "durabilidade": "Alta", "clima": "Baixa (Estável)", "revestimento": "Ouro", "fixacao": "Ball-end", "tolerancia": "Média", "confiabilidade_preco": "Baixa"},
    {"nome": "Pyramid 130 000 Syntha-Core Violin with Plain 1st, Ball End", "projecao": "Moderada", "cor": "W: 57% | F: 56%", "nucleo": "Sintético", "preco_min": 149, "preco_max": 196, "resposta": "Média", "ambiente": "Câmara", "qualidade": "B+", "nota": "7.42", "amaciamento": "Longo (Vários dias)", "durabilidade": "Média", "clima": "Média", "revestimento": "Alumínio / Níquel", "fixacao": "Ball-end", "tolerancia": "Alta", "confiabilidade_preco": "Baixa"},
    {"nome": "Smart", "projecao": "Moderada", "cor": "W: 20% | F: 70%", "nucleo": "Aço (Sólido)", "preco_min": 31, "preco_max": 53, "resposta": "Rápida", "ambiente": "Ambos", "qualidade": "C-", "nota": "5.00", "amaciamento": "Rápido (minutos)", "durabilidade": "Longa (6+ meses)", "clima": "Baixa (Estável)", "revestimento": "Níquel (Níquel)", "fixacao": "Ball-end", "tolerancia": "Alta", "confiabilidade_preco": "Média"},
    {"nome": "Strinberg VS4", "projecao": "Moderada", "cor": "W: 20% | F: 70%", "nucleo": "Aço (Sólido)", "preco_min": 37, "preco_max": 57, "resposta": "Rápida", "ambiente": "Ambos", "qualidade": "C-", "nota": "5.00", "amaciamento": "Rápido (minutos)", "durabilidade": "Longa (6+ meses)", "clima": "Baixa (Estável)", "revestimento": "Níquel (Níquel)", "fixacao": "Ball-end", "tolerancia": "Alta", "confiabilidade_preco": "Média"},
    {"nome": "Super-Sensitive Red Label", "projecao": "Moderada", "cor": "W: 30% | F: 60%", "nucleo": "Aço (Sólido)", "preco_min": 121, "preco_max": 180, "resposta": "Rápida", "ambiente": "Interno", "qualidade": "C", "nota": "7.50", "amaciamento": "Rápido (minutos)", "durabilidade": "Longa (6+ meses)", "clima": "Baixa (Estável)", "revestimento": "Níquel", "fixacao": "Ball-end", "tolerancia": "Alta", "confiabilidade_preco": "Média"},
    {"nome": "Super-Sensitive Sensicore", "projecao": "Moderada", "cor": "W: 70% | F: 50%", "nucleo": "Sintético (Perlon)", "preco_min": 240, "preco_max": 350, "resposta": "Moderada", "ambiente": "Interno", "qualidade": "B-", "nota": "8.00", "amaciamento": "Médio (1-3 dias)", "durabilidade": "Média (2-4 meses)", "clima": "Baixa (Estável)", "revestimento": "Alumínio / Prata", "fixacao": "Ball-end", "tolerancia": "Alta", "confiabilidade_preco": "Média"}
];